### ISSUE TITLE
Checking feasibility of PR

### ISSUE THREAD

**Issue by bjohas** [bwiernik/zotero-shortdoi#12]
Hello @bwiernik,

We'd like to do a PR on zotero-shortdoi, so that the plugin can trigger another plugin (if that plugin is installed). The only change to zotero-shortdoi would be this triggering action (unless you want some of the proposed functionality in zotero-shortdoi).

Our plugin will give items a unique ID, that is visible to the user (you may know form the forum that I have been experimenting with this). If a doi/short-doi is available, this will be used (and added to "Loc In Archive"). If no doi is available, then an ID will be generated (libraryID:itemKey), see https://github.com/retorquere/zotero-edtechhub/issues/5. 

For this to run reliably, zotero-shortdoi would have to run first, triggering our plugin. Does that sound ok? If yes, @retorquere would do a PR.

**Comment by retorquere** [comment]
Wait, then I misunderstood earlier. If that's all you want I can just listen for item changes.

**Comment by bwiernik** [comment]
@bjohas Yeah, I think that you don't need any changes from me. Just add a listener to your own plugin (you can copy the code I use to listen for new item additions, for example). 

I'd suggest just looking for and using the long DOI (perhaps looking for a shortDOI in Extra as a backup). In the near future, I switch to storing shortDOIs in Extra under `shortDOI:` and leaving the full DOI intact in the Zotero field.

**Comment by bjohas** [comment]
OK, that's great - many thanks. How "near" is the "near future"? :)
