### ISSUE TITLE
Zero-width space char disappearing

### ISSUE THREAD

**Issue by njbart** [bwiernik/zotero-shortdoi#2]
With “Zotero DOI Manager” enabled, zero-width space chars entered in the author first name field disappear after a few seconds. With “Zotero DOI Manager” disabled, no such effect occurs.

Any ideas why/how Zotero DOI Manager could be causing this?

Background: citeprocs remove spaces after particles ending with an apostrophe. One name where this must not happen is “Lorenzo de’ Medici”, and entering this as [Medici][Lorenzo de’\<ZWS\>] has been working well so far.

**Comment by bwiernik** [comment]
Can’t replicate this behavior https://forums.zotero.org/discussion/comment/297081/#Comment_297081
