### ISSUE TITLE
Reference to  GitHub.org instead od GitHub.com in add-on description result in non-existing page

### ISSUE THREAD

**Issue by danieltomasz** [bwiernik/zotero-shortdoi#24]
The addon desription when checking in the Zotero refer to https://github.org/bwiernik/zotero-shortdoi this site doesn't exist

**Comment by bwiernik** [comment]
Your version of the plugin is out of date. This was fixed years ago.

**Comment by danieltomasz** [comment]
My version is 1.3.9 the latest that is available as precompiled xpi 
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/7980381/101247430-ede74980-3719-11eb-8284-45c0c2d9f4f9.png">
