### ISSUE TITLE
Shouldn't getPref and setPref be methods in Zotero.ShortDoi ? 

### ISSUE THREAD

**Issue by denismaier** [bwiernik/zotero-shortdoi#25]
https://github.com/bwiernik/zotero-shortdoi/blob/6d52a6ce323c24982a67010e3dcb52730cc911d6/chrome/content/scripts/zoteroshortdoi.js#L9

I've tried using your version of `getPref` and `setPref` in a plugin I'm working on. But when I've loaded your and my plugin at the same time, your version of `getPref` would always overwrite my version. The methods in my plugin live now in `Zotero.swisscoverylocations`, and now it's working, but I was wondering whether there's a reason why `getPref` and `setPref` are not methods in Zotero.ShortDoi?

**Comment by bwiernik** [comment]
Probably just sloppiness on my part--that part is fairly patched together. I'd be happy for a pull request if you've got some time.

**Comment by denismaier** [comment]
>  I'd be happy for a pull request if you've got some time.

Sure.
