### ISSUE TITLE
Some documents can be found on sci-hub, but doi is not available.

### ISSUE THREAD

**Issue by nigeder** [bwiernik/zotero-shortdoi#29]
Can you support some literatures that can be found in sci-hub to obtain doi through the short-doi plug-in, such as the article "A Sensitivity Analysis of Cross-Country Growth Regressions", the link is [https://www.jstor.org/stable/2117352](https://www.jstor.org/stable/2117352)

**Comment by bwiernik** [comment]
That item doesn't have a DOI, at least not reported on that page. The "10.2307/2117352" in the JSTOR data is not a DOI, but a JSTOR identifier that they very irresponsibly decided to make mimic a DOI. 

See here that that ID does not resolve in the DOI system. https://doi.org/10.2307/2117352

I would recommend using another source for article data aside from JSTOR whenever possible.
