### ISSUE TITLE
Access DOI?

### ISSUE THREAD

**Issue by fredericky123** [bwiernik/zotero-shortdoi#3]
can this plugins add doi to selected item rather than verify doi? 
you know many items imported from Google Scholar do not have doi information
this website can search for doi information using item title: https://www.crossref.org/

**Comment by bwiernik** [comment]
It’s on my radar to add support for DOI lookup, but no promises on when it might be done

**Comment by fredericky123** [comment]
Great, as long as you finish it, a lot of people will appreciate you so much

**Comment by sdspieg** [comment]
Hear, hear!

**Comment by bwiernik** [comment]
Added in https://github.com/bwiernik/zotero-shortdoi/commit/640962ed0c42b6bb6942142be8f3fc29526a1c91

**Comment by fredericky123** [comment]
Thanks sooo  much!!!

**Comment by bwiernik** [comment]
It's currently a very slow process and doesn't provide the best feedback. I'll work on refactoring it as an asyncrhonous process, but no ETA on that.

**Comment by fredericky123** [comment]
Right now it is convenient to use, the improvement will be better!
