### ISSUE TITLE
couldn't update doi only from paper title

### ISSUE THREAD

**Issue by bugsuse** [bwiernik/zotero-shortdoi#30]
zotero-shortdoi couldn't extract when I just provide the paper title, such as 'Cloud-top properties of growing cumulus prior to convective initiation as measured by Meteosat Second Generation. Part I: Infrared fields'.

version: 
MacOS 10.15.7
zotero 5.0.96.3
zotero-shortdoi latest release

Thanks so much!

**Comment by bwiernik** [comment]
That's expected. The CrossRef API requires at least the title and publication title.
