### ISSUE TITLE
Causes Zotero to crash when importing paper via Zotero Connector in chrome

### ISSUE THREAD

**Issue by DeadDjembe** [bwiernik/zotero-shortdoi#33]
importing a paper into Zotero from Chrome via the Zotero Connector chrome extension causes Zotero to crash.  I tracked it down to this extension versions 1.4.1 and 1.4.2. The version 1.4.0 does not cause Zotero to crash.  

Having only this extension enabled causes the issue, but disabling only this extension and enabling all my other extension does not replicate the problem.  DOIs are accurately identified and added to the paper upon restarting Zotero. I am on Mac OS using Zotero 5.0.96.4.

**Comment by bwiernik** [comment]
Does this happen every time you import, or only in some circumstances? With just a single item or only for large batches?

**Comment by DeadDjembe** [comment]
It was happening only when importing with the Chrome extension Zotero Connector.  It did not happen when importing by adding a PDF directly to Zotero.  However, the issue seems to have corrected itself.  There was an update for Chrome that appears to have fixed the issue - I have tested Zotero Connector import (same paper into same collection that causes the crash) with ShortDOI versions 1.4.0, 1.4.1, and 1.4.2 and all are working as expected.  This ticket can be closed and we can blame Google for the issue :)

**Comment by bwiernik** [comment]
Okay!
