### ISSUE TITLE
How to customize the tags?

### ISSUE THREAD

**Issue by fredericky123** [bwiernik/zotero-shortdoi#5]
Actually, I do not want  the plugins to generate tags of "multiple dois" or "no dois" automatically, can I customize that?

**Comment by bwiernik** [comment]
Not currently, but I’ll add that in a future version when I have a chance to work on it.

**Comment by bwiernik** [comment]
Customizable tags added in https://github.com/bwiernik/zotero-shortdoi/commit/a1a0f2b73d51d4b33d9b7059f77dad21fa9f6aa2

**Comment by fredericky123** [comment]
Thanks very much!
