### ISSUE TITLE
can get the long doi automatically?

### ISSUE THREAD

**Issue by fredericky123** [bwiernik/zotero-shortdoi#8]

**Comment by bwiernik** [comment]
Added this option in https://github.com/bwiernik/zotero-shortdoi/commit/566547a3d1783fa9501f68fdc905fc6be7d77d94

Thanks!

**Comment by fredericky123** [comment]
Thanks very much!
A small question, for example, the exact citation is 
MacDonald G, Ryall M. Do new entrants sustain, destroy, or create guaranteed profitability? Strat Mgmt J. 2018;39:1630–1649. https://doi.org/10.1002/smj.2770
however, for now, this add-on' s effect is 
MacDonald G, Ryall M. Do new entrants sustain, destroy, or create guaranteed profitability? Strat Mgmt J. 2018;39:1630–1649. https://doi.org/10.1002/SMJ.2770

can you use the lower case?

And another small question: are you interested in getting the Journal Abbreviation? Will you make an add-on  in the future?

**Comment by bwiernik** [comment]
Upper vs lower case doesn’t matter. DOI are case insensntive. 

Considering that Zotero can automatically abbreviate journal titles in the word processor plugins regardless of the content of the Journal Abbr field, I don’t see much value in a plugin for that, and it would be a lot more complicated to build than this one.

**Comment by fredericky123** [comment]
Oh really, I haven't know this function. Do I need some settings to make Zotero to abbrebreviate journal titles? Here is my current citation example:
![image](https://user-images.githubusercontent.com/13982749/49091821-92b52d80-f29b-11e8-87f7-2e5fa307b95a.png)

as you can see ,it is full name

**Comment by bwiernik** [comment]
What style are you using? And are you using the Word plugin to add the citations, or just dragging them from Zotero?

**Comment by fredericky123** [comment]
APA 6th, and I am using Word plugin

**Comment by bwiernik** [comment]
APA doesn’t use Journal abbreviations at all. Choose a style that does.

**Comment by fredericky123** [comment]
OK, thanks.
